* Sulforafano y sus Efectos en el Cáncer, mortalidad, Envejecimiento,
Cerebro y Comportamiento, Enfermedades Cardiácas y más
  :PROPERTIES:
  :CUSTOM_ID: sulforafano-y-sus-efectos-en-el-cáncer-mortalidad-envejecimiento-cerebro-y-comportamiento-enfermedades-cardiácas-y-más
  :END:

En este vídeo se trata sobre uno de los caminos biológicos más
importantes conocido como /NRF2/, y el mayor inductor en activar este
camino actualmente se conoce como /Sulforafano/.

** Resumen
   :PROPERTIES:
   :CUSTOM_ID: resumen
   :END:

Los efectos del Sulforafano y derivados son:

-  Reducción dramática en la inflamación y daños al ADN en humanos y el
   rol que esto puede jugar en el proceso de envejecimiento y prevención
   de enfermedades.
-  Reducciones masivas en el riesgo de padecer cáncer en humanos y su
   eficacia como propio tratamiento en pacientes con cáncer,
   particularmente en cáncer de próstata.
-  Cambios profuncos en biomarcadores de lípidos, reduciendo
   enfermedades cardiácas hasta el 50%.
-  Posible implicación en desórdenes neurodegenerativos y lesiones
   cerebráles traumáticas
-  Se ha demostrado ser tan efectivo como el Prozac en ratones en el
   tratamiento de la depresión y en 10 modelos distinso de animales.
-  Reducciones importantes en cuanto al comportamiento de los humanos en
   ciertas enfermadades neurologicas, como autismo.
-  Aumentos drámaticos en la excreción de ciertos componentes
   contaminantes del aire y carcinogénicos en los cigarros (hasta un 60%
   de excreción) en humanos.

** ¿Qué es el Sulforafano?
   :PROPERTIES:
   :CUSTOM_ID: qué-es-el-sulforafano
   :END:

El Sulforafano es un miembro muy poderoso miembro de una gran familia de
componentes conocidos como Isotiocianatos. Estos compuestos se forman
cuando los miembros de la familia Brassica de las verduras, conocidos
como verduras crucíferos se trituran, pican o mastican.

Aunque exiten muchos tipos distintos de Isotiocianatos, en este vídeo
Rohonda se centra en el Sulforafano debido a su enorme y aún en
expansión cantidad de investigación realizado sobre él, que además ha
demostrado una y otra vez su propieades beneficiosas. Estas propiedades
varian desde anti cancerigenas hasta cambioes en el estado anímico.

** El Sulforafano es barato.
   :PROPERTIES:
   :CUSTOM_ID: el-sulforafano-es-barato.
   :END:

Esto se debe a un estudio en los años 90: el precursos del Sulforafano,
Glucorapanina, se encuentra en los brotes de brócoli a niveles variando
entorno a 50-100 veces más que el que se encuentra en el brócoli
crecido.

** 3 libras a la semana
   :PROPERTIES:
   :CUSTOM_ID: libras-a-la-semana
   :END:

Se necesitan entorno a 6 tarros de cristal para producir 3 libras de
brotes de brócoli a la semana para recolectar entorno a 8 onzas de
brotes frescos por tarro. $25 de semillas de brócoli produciran
bastantes libras de brotes para poder consumir estas verduras tan sanas
durante semanas.

** Notas sobre el vídeo
   :PROPERTIES:
   :CUSTOM_ID: notas-sobre-el-vídeo
   :END:

*** Prevención del cáncer
    :PROPERTIES:
    :CUSTOM_ID: prevención-del-cáncer
    :END:

En 2011 se publico un estudio en el /American Journal of Clinical
Nutrition/ que mostró que si se divide a la población en base a su
consumo de verduras, aquellso que en el top 20% comiendo la maytyor
cantidad de verduras tenian una reducción del 16% en lo que se conoce
como all cause mortallinty. Lo que significa es que durante el tiempo
que duró el estudio, esta gente tenia un 16% menos de posiblididda de
morir de algo no relacionado con accidentes. Pero si en lugar de solo
mirar al consumo de verduras, se mira al top de gente que come verduras
crucíferos, los efectos en all caouse mortallituy es más sustancial, el
20% de la gente que consme esta verduras reducen su tasa de muerte al
22%. solo eso ya es suficiente para empezar a comer brócoli. Ya que hay
correlaciones muy fuertes entre el cosummo de brocoi y cancer.

Los hombres que comen de 3 a 5 servring de estas verduras tenian una
reducción del 40% de padecer cáncer de próstata comparado a hombre que
comen menos de una racióni por semana. Otro estudio, hombres que comen
dos o más raciones de media taxa de brocoli a la semana tenian 44% menos
probabilidad de padecer cancer de bladder. Fumadores que cosumen al
menos 4 y medos raciones de verduras de estas al mes, 55% reducción en
cáncer de pulmón comparado a fumadores que toman menos de dos/2 raciones
al més. Multiples estudios, muestran que mujers que comen varieadds de
verduras cruciferas al menos una vez a la semana tienen hasta un entre
un 17 al 50% menos posiblilidades de padecer cáncer de pecho comparadas
con aquellas que la cosumen cada dia. Las variacinoes de estos
resultados pueden deverse a como se consumen las verdudas, si se cocinan
o no.

*** Para gente con cáncer
    :PROPERTIES:
    :CUSTOM_ID: para-gente-con-cáncer
    :END:

La gente con cáncer de vejiga comiendo 4 raciones de raw broccoli a lmés
tuvieron una reducción del 57% en la tase de mortalidad y un 43%
reducción en all cause mortality comparada con aquellos tomando una sola
ración al més.

Está claro que hay una fuerte asociación entre el consumo de brocoli y
salud. Pero antes de afirmarlo hay que estasblecer un mecanimos
plausible, el mecanismo más probable es el Isothiocyanates.

*** Isothiocyanates
    :PROPERTIES:
    :CUSTOM_ID: isothiocyanates
    :END:

Se forman mediante componentes conocidos como glucosinolates a través de
una enzima llamada myrosinase. Esta enzima se activa cuando el tejido de
la planta crucífera se crushed, corta o mastica. Pero se desactiva bajo
condiciiones como mantenerlas a altas temperaturas durante mucho tiempo,
como en la cocción.

Un tipo particular de Isothiocyanates, el Sulforaphane destaca sobre el
resto, particularmente debido a la gran cantidad de estudios que se han
realizado sobre ella. El glucosinolate precursor del sulforaphane es el
glucoraphanin. Los brotes de brocoli pueden contener hasta 100 vecees
más de este precursos que el brócoli.

El sulforaphane reduce el riesgo de cancer y mata a las céluslas
canrecígenas. Un mecanismo de prevención es la desactivación de la fase
1 de biotransformación de las enzimas. Estas encimas son responsables de
convertir procarcinógenos a carcinógenos activos. Sulforaphane puede
prevenir DNA adducts, un tipo de daño al ADN que se ha demostrado
degenera en cancer.

El humo del tabaco está repleto de carcinógenos que forman DNA adducts.
Esto incrementa el riesgo de áncer de bejiga. Comer al menos 4.5
raciones de verduras crucíferas al mes se ha asociado con el decremento
de padecer cáncer de pulmón hasta un 55%. De igual manera, en un estidio
el que se le proporciona a las ratas un componente que causa cáncer de
vejiga, el grupo que no tomaba est etipo de verduras desarrolló cáncer
(un 95% de las ratas), mientras que otro grupo de ratas, tomando el
mismo componente que provaca cáncer y también las verduras crucíferas
desarroolaron cancer solo el 37% de las ratas, y además sus cáncers eran
mucho más pequeños. Otros estudios con otros animalas han demostrado que
el Isothicynates reducen el cáncer. Para el cáncer de próstata pasa
igual. Hombres con c. de prostata a los que se les da 60mg de
sulforaphane al día, en forma de unos 140g de brotes de brócolis
redujeron la tasa que mide por cuanto se dobla el tamaño del tumor en
hasta (PSA) hasta un 86% comparado con el placebo. En otro estdio, se
usó 35mg de sulforaphane y se redujo también la tasa, pero redujo en un
57%. Para el cáncer de mama, 37mg de sulforaphane (85g de brotes) se
encontró la acumulación de este componenete en el contenido del cáncer
de pecho. Esto quiere decir que la molécula de hecho llega al tejido con
cáncer.

https://youtu.be/zz4YVJ4aRfg?t=479
