Dr. Rhonda Patrick speaks with Dr. Valter Longo, a professor of
gerontology and biological sciences and director of the longevity
institute at the University of Southern California. Dr. Longo has made
huge contributions to the field of aging, including the role of fasting
and diet in longevity and healthspan in humans as well as metabolic
fasting therapies for the treatment of human diseases.

In this conversation, Rhonda and Valter discuss... - The effects of
prolonged fasting, which refers to 2-3 day fasting intervals in mice and
4-5 days in humans. - Dr. Longo's work on the fasting-mimicking diet,
which is 5 day restricted diet that is meant to simulate some of the
biological effects of prolonged fasting while still allowing some food.
- How clinical trials have demonstrated efficacy for this diet for type
2 diabetes, multiple sclerosis, and cancer patients. - Fasting as an
inducer of differential stress resistance, where it can simultaneously
make cancer cells more sensitive to death while also making healthy
cells more resistant to these same death stimuli (such as chemotherapy)
which might otherwise induce cell death amongst healthy cells as
collateral damage. - Fasting as a biological state which humans
historically experienced with extreme regularity and we may ultimately
need in order to mitigate various disease states. - The effects of
prolonged fasting on the immune system, namely, how it clears away
damaged white blood cells via autophagy and how this causes
hematopoietic stem cells to self renew and make more stem cells and also
produce new blood cells to fully replenish the white blood cell
population. - How prolonged fasting causes a shift in the immune cell
population towards one that is more representative of youth by
normalizing the ratio of myeloid cells to lymphoid cells. - The positive
effects of prolonged fasting and the fasting-mimicking diet on markers
of systemic inflammation, blood glucose levels and other aging
biomarkers. - The conclusions of Dr. Longo & Dr. Marcus Bock's research
comparing 1 week of the fasting-mimicking diet followed by 6 months of
mediterranean diet to six months of a ketogenic diet in people with
multiple sclerosis. - The strange, somewhat paradoxical role of
autophagy genes in cancer progression and some of the open questions
surrounding the exact role that these genes are playing. - Dr. Longo's
high level thoughts on metformin as an anti-aging drug. - How the growth
hormone/IGF-1 axis is one of the most important genetic pathways in
aging from yeast to worms to mice to humans. - The effects of prolonged
fasting, which refers to 2-3 day fasting intervals in mice and 4-5 days
in humans. - Dr. Longo's work on the fasting-mimicking diet, which is a
5-day restricted diet that is meant to simulate some of the biological
effects of prolonged fasting while still allowing some food. - Day 1 -
1,090 calories (10% protein, 56% fat and 34% carbohydrate). - Days 2
through 5 - 725 calories (9% protein, 44% fat and 47% carbohydrate). -
How clinical trials have demonstrated efficacy for this diet for type 2
diabetes, multiple sclerosis, and cancer patients. - Fasting as an
inducer of differential stress resistance, where it can simultaneously
make cancer cells more sensitive to death while also making healthy
cells more resistant to these same death stimuli (such as chemotherapy)
which might otherwise induce cell death amongst healthy cells as
collateral damage. - A clinical trial Dr. Longo was involved in that
combined fasting with chemotherapy which showed that cancer patients
that fasted for at least 24 hours and up to 72 hours prior to undergoing
chemo had their IGF-1 levels (which promote cancer growth) decreased,
and also found preliminary evidence that normal lymphocytes had lower
DNA damage in those individuals that fasted prior to chemo compared to
not fasting. In other words, fasting prior to chemo was associated with
an overall reduction in toxic-sides effects on the immune system,
including chemo-associated myelosuppression. - The effects of prolonged
fasting on the immune system, namely, how it clears away damaged white
blood cells via autophagy and apoptosis and then induces hematopoietic
stem cells to self-renew, making more stem cells, which then produce new
blood cells to fully replenish the white blood cell population. This has
the effect of recycling the immune system: Valter's research showed that
fasting for 48 hours in mice resulted in a temporary 28% decrease in
white blood cell number. - How prolonged fasting causes a shift in the
immune cell population towards one that is more representative of youth
by normalizing the ratio of myeloid cells to lymphoid cells. - The
positive effects of prolonged fasting and the fasting-mimicking diet on
markers of systemic inflammation, blood glucose levels and other aging
biomarkers. - How the fasting-mimicking diet holds promise in treating
autoimmune disease such as multiple sclerosis (MS). Mice with MS on the
fasting-mimicking diet for 3 days every 7 days for 3 months reduced MS
symptoms in all mice and 20% of those animals fully recovered. - A small
trial in humans showed with MS conducted by Dr. Longo & Dr. Marcus Bock
comparing 1 week of the fasting-mimicking diet followed by 6 months of
Mediterranean diet to six months of a ketogenic diet in people with
multiple sclerosis. - Fasting as a biological state which humans
historically experienced with extreme regularity and we may ultimately
need in order to mitigate various disease states. - The strange,
somewhat paradoxical role of autophagy genes in cancer progression and
some of the open questions surrounding the exact role that these genes
are playing. - Dr. Longo's high-level thoughts on metformin as an
anti-aging drug. - How the growth hormone/IGF-1 axis is one of the most
important genetic pathways in aging from yeast to worms to mice to
humans.

* Notas
  :PROPERTIES:
  :CUSTOM_ID: notas
  :END:

** Fasting mimicking Diets (FMD) Breakdown:
   :PROPERTIES:
   :CUSTOM_ID: fasting-mimicking-diets-fmd-breakdown
   :END:

-  Day 1: 1090cal (10% prot, 56% fat, 34% carbs)
-  Day 2-5: 725 cal (9, 44, 47)

** Caloric restriction (CR) vs Periodic fasting (PF)
   :PROPERTIES:
   :CUSTOM_ID: caloric-restriction-cr-vs-periodic-fasting-pf
   :END:

-  Former: se reduce la ingesta de calorias un 30%. Later: more extreme
   deficit, for shorter duration
-  PF tiene fases separadas, CR no. Al someter al cuerpo al déficit las
   celulas madre se activan, pero se regeneran al volver a comer (Es más
   beneficioso).
-  PF produce ketone y incrementa autophagy. CR y PF mejoran el
   metabolismo e incrementan stress response genes.
-  PF can also stimulate the hematopoieic stem cells, which leads to a
   lineage-balanced hematopoitic regeneration.

Autophagy: Used to get rid of damaged cells through a process by which
the cell degrades its components, including organelles and proteins.
This mechanism help to protect against cancer and even aging by reducing
the burden of abnormal cells. During Fasting cellular autophagy is
enhanced in order to provide energy for surviving cells.

Apoptosis: Cellular program that causes a cell to kill itself after
damage has occurred. One of the ways that multicellular organism protect
themselves from cancer. MCL1 es una anti-apoptotic protein.

Cuando se hacen FMD, se pierden el 40% de los globulos blancos, pero
luego al comer se regeneran por completo. ESta regeneración no ocurre
más en la vida casi desde el dia de nacimiento, pero con FMD se puede
emular. Es como recosntruirse de nuevo. Al hacer FMD el sistema se hace
más pequeño, encoges los organos, y luego vuelves a reconstruirlos al
comer. Y es el cuerpo mismo el que se reconstruye a sí mismo. Muy
beneficioso para aging.

*Immunosenescence*: Process of deterioration that occurs with age. Cells
that acquired enough damage can becvome senescent (they are not
metabolically active and do no serve a function). They can release
inflammatory cytokines which can then lead to the damage of neighboring
healthy cells. When this occurs to our inmmune cells, it is called
imm.....

Paper de los japos de centenarios, supercentenarios etc. El marcador más
relacionado con el aging process era la inflamación. Longo dice que el
crees que es al revés, aging es la causa de la inflamación. Pero la
inflamación aún así es un marcador importante.

*C-Reactive Protein* (CRP): y Interleukin-6 (IL-6) junto a otros, como
TNF-alpha. Todos biomarcadore de inflamación. En las analíticas es mejor
tener estos biomarcadores bajos.

Damaged cells can go on to become as senescent cells, cells that no
longer are performing their function and produce inflammatory cytokines.
This can damage nearby tissue over time.

** Cómo transladaror a humanos (el FMD)
   :PROPERTIES:
   :CUSTOM_ID: cómo-transladaror-a-humanos-el-fmd
   :END:

Para pacientes de cáncer, les daban una bolsa con la comidad para el
día. Para Multiple sclerosis, FMD redujo la severidad de la enfermedad
en todos los animales, y la curó por completo en el 20%. Ahora los
doctores están recomendando a los pacientes que hagan FMD, pacientes de
cancer y MS (multple sclerosis), porque deja al cuerpo repararse a sí
mismo.

** Differential Stress Resistance
   :PROPERTIES:
   :CUSTOM_ID: differential-stress-resistance
   :END:

Normal cells being more resilient to stress because they can increase
genetic pathways that help protect against stress whereas cancer cells
are unable to do this as a consequence of oncogenic signaling.
Differencial stress sensitization refers to the fact that cancer cells
are more sensitive to cell death as a consequence to stress.

Hay que creer a este doctor porque su trabajo es profundamente único, ha
ido estudiando los comportamientos desde un organismo, hasta animalas,
ratas y finlamente humanos, y comprobado que funciona.

Razón?, starvation mode

** Starvation mode
   :PROPERTIES:
   :CUSTOM_ID: starvation-mode
   :END:

Fasting results in ketogenesis, promotes potent changes in metabolic
pathways and cellular processes such as stress resistance, lipolysis and
autophagy. Induces cancer cell death by the production of reactive
oxygen species (ROS) throught mitochondrial activation.

Por ejemplo, ecoli cuando no tiene comida se protege, hasta que llega la
comida. Cuando haces que las celulas pasen hambre, las buenas se
protegen, pero las celulas de cancer mueren, porque no saben
protegerse.(Son oncogenes)

** Oncogenes
   :PROPERTIES:
   :CUSTOM_ID: oncogenes
   :END:

Gene with the potencial to cause cancer. Proto-oncogene es el gen normal
que regula el crecimiento celular y proliferación, pero si muta no mata
a la celula cuando debe, la deja activa y esta se reproduce, cuando
debería haber muerto.

Las celulas cancerigenas son muy tontas. Han evucionado teniendo un
monton de alimentos al rededor, azucar, proteinas, etc. Cuando las dejas
sin comida se mueren. Con la kimioterapia estás haciendole mas daño a la
celula buena. Al cancer le encanta el azucar, y amino acid glutamine.
Cuando quitamos la abundancia, la celula cancerigena no sabe obtener
alimento y muere. FMD junto con quimioterapia es una muy buena de matar
por completo el cáncer.

FMD ha demostrado que incrementa el numero de cytotoxic T lymphocytes,
un tipo de celula inmune que mata cancer cells.

Combinar FMD con kimio está dando muy buenos resultados, por separado no
dan tan buenos resultados.

Fasting no es estres, es más al revés, el comer es más estresante para
el cuerpo que no comer. A lo largo de la historia el ser humano ha
estado largos periosdos sin comida. Incluso meses. Fasting es el mundo
normal, comer es lo extraño.

Cuado a las celulas cancerigenas le quitas la glucosa, no tienen más
remedio que volver a la mitocondria (Oxidative Phos..)

** Oxidative Phosporylation
   :PROPERTIES:
   :CUSTOM_ID: oxidative-phosporylation
   :END:

Process of generating energy that occurs when the mitochondria couple
oxygen with electrons that have been derived from different food sources
including glucose, fatty acids, and amino acids.

** Cytotoxic T Lymphocytes
   :PROPERTIES:
   :CUSTOM_ID: cytotoxic-t-lymphocytes
   :END:

A type of white blood cell that kills cancer cells, cells that are
infected (normally with viruses) or are otherwise damaged.

Fasting hace que las celulas cancerígenas sean identificads por los
globulos blancos.

El doctor hace fasting, no desayuna. Hay que usarlo en una forma
flexible. Si tiens sobrepeso, dos comidas al dia. Si estás delgado, tres
comidas al dia, pero Time Restricted feeding en una ventana de 12 horas
o menos. Excess visceral fat, is linked to type 2 diabetes, insuline
resistance, inflammatory diseasses, and other obesity-related diseasses.

** Beta-Hydroxybutyrate
   :PROPERTIES:
   :CUSTOM_ID: beta-hydroxybutyrate
   :END:

A ketone body synthesized in the liver from acetyl-CoA when fasting or
in ketosis.

hay que centrarse en mantener a la gente feliz, a la vez que prolongar
la salud y la vida. Aunque no lo parezca, la gente ha hecho y hace CR
durante siglos, y actualmente se sigue haciendo. Por ejemplo, en italia
muchas familias comen dos veces al dia, japón, california etc.

Lo minimo que hay que dejar son 12 horas sin comer, a más mejor. Pero 12
está bien para empezar. Lo ideal saltarse el desayuno. La PFM diet, se
puede hacer de vez en cuando, cada dos o tres meses hacerla, 5 dias
restingiendose.

Rohonda lo hace así, 14 horas de fasting, 10 para comer.

/Once liver glycogen is depleted, fatty accids begin being transported
to the liver to be converted into ketone bodies, such as
beta-hydroxybutyrate. These ketone bodies are then transported to a
wide-variety of tissues and used for energy./

FMD promotes multi system regeneration. A partir del dia dos mas o
menos, el cuerpo pasa a generar ketones y usarlos como fuente de
energia, aquí usa la grasa visceral como fuente, y la quema. (Esto me
paso a mi) El cerebro empieza a quemar ketones en vez de glucosa. Los
organos empiezan a hacerse más pequeños. Para luego regenerarse. Esto
solo se logra con FMD.

En el estdio que hizo con ratas con MS, tras la regeneración el 20% de
las ratas curaron la enfermedad por completo, el 80% tuvo mejoras
significativas en la enfermedad. Al regenarr las celulas, ya no son
autoinmmunes, no se atacan a sí mismas, por tanto las alergias se pueden
curar (en este caso MS).

** FMD holds promise in treating autoimmune disease.
   :PROPERTIES:
   :CUSTOM_ID: fmd-holds-promise-in-treating-autoimmune-disease.
   :END:

Mice with MS on FMD for 3 days every 7 days for 3 months showed reduced
MS symtoms in all mice and 20% fully recovered. Autoinmune cells died
and were replaced by new immune cells. FMD also stimulated remyelination
and regeneration of oligodendrocytes. Paper: Choi, In Young et al "A
diet Micmicking Fasting promotes Regeneration and reduces autoimmunity
and MS symtos" Cell reports 15.10 (2016).

LA inflamación en este estudio bajó, principalmente n la espina dorsal,
lo que permitió a los progenitors cells? las que reconstruyen, regeneran
el sistema. Matas a las malas, pones nuevas y reconstruyes la espina
dorsal. No es magia, es como cuando te cortas, el cuerpo se regenera.

** Otro estudio, con dieta mediterranea.
   :PROPERTIES:
   :CUSTOM_ID: otro-estudio-con-dieta-mediterranea.
   :END:

1 semana de Fasting, con una dieta mediterranea, derivó en 6 meses de
ketone diet, continua. Era, 1 semanas de FMD, y luego 6 meses de dieta
mediterranea. Van a proponer un ciclo cada dos meses. PAra ver si
funciona igual de bien.

Para los autoimmune diseases funcioa bien, los cura. (Chron, MS,
alergias).

*Glycerol*: A sugar-alcohol compound that is the backbone of the
triglycerides.

*Ketone bodies*: Molecules produced by the liver from fatty acids during
periods of low food intake (fasting), carbs restrictive diets,
starvation or prolonged intense exercise. Examples: acetoacetate,
beta-hydroxybutyrate, and acetone. Thes ketone bodies are readily used
as energy for a diverse array of cells types, including neurons.

*Gluconeogenesis*: Metabolic pathway in which the liver produces glucose
from non-carbs substrates including glycogenic amino acids (from
protein) and glycerol (from lipids).

Las grasas son una fuente de energia para las celulas madre, para
regenerar el higado tras un mes de fasting, por ejemplo. Podrían
regenerar hasta medio higado.

-  Caloric restriction mimetics enhance anticancer immunosurveillance.
   (paper)

*Insuling-like Growth Factoc (IGF-1)*: One of the most potent natural
activators of the AKT signaling pathway, stimulator of cell growth and
proliferation, potent inhibitor of programmed cell death, primary
mediator of the effects of growth hormone, and has been implicated in
contributing to aging and enhancing the growth of cancer after ir has
been initiated. Similar in the molecular structure to insulin, IGF-1
plays a role during childhood for growth and continues later in life to
have anabolic, as well as neurotrophic effects. Protein intake increases
IGF-1 levels in humans, independent of total caloric consumption.

Aminoácidos y proteinas controlan dos pathways mayoritariamente. 1 la
growth hormonoe (IGF-1), y otro que no me entero, ambos son ampliamente
reconocidos de ser proaging pathways.

*Single Nucleotide Polymorphism (SNP)*: A change ina one nucleotide DNA
squence in a gene that may or may not alter the function of the gene.
SNPs affect phenotype such as hair and eye color, but also our disease
risk, the way we absorb and metabolize micronutrients, macro and much
more.

FOXO3: Gene for which increases in activity have been associated with
longevity. FOXO3 is a master regulator of many genes involved in dealing
with stress. Including DNA repair genes, protein misfolding genes,
antioxidant genes, anti inflamatory etc. Humans with a more active
versino of this gene have a 2.7 fold increased chance of living to be a
centenarian.

*IGF-1*: has a potent growth effect on a variety of cancer cells, by
increasing the proliferation rate (cells multiply) and inhibiting
apoptosis (Cell death), therefore, allowing cancer cells to overcome
normal checkpoints that will usually induce the cancer cell to die.
Luego IGF-1 incrementa la posibilidad de cancer (No tomar tanta
proteina).

A más IGF-1, menos FOXO3. No todo IGF-1 es malo, como todo, en su justa
cantidad, juega un papel importante en el crecimiento muscular y
reparación.

IGF-1 plays important tole in muscle growth/repair and helpful in
growing new brain cells. Fasting causes IGF-1 to go down. Re-feeding
causes IGF-1 to go up. Longo points out that this is a distiction of
fasting from caloric restriction, which involves a sustained reduction
in intake. Es IGF-1 el causante de que en el FMD se reparen las cosas.

El ejercicio es muy bueno porque se basa en lo mismo, dañas el músculo y
luego lo reparas, con el tiempo vas regenerando el músculo por completo,
aunque más lentamente que con FMD. En combinación con fasting es ideal.

En el libro del doctor, habla del ejercicoi y la necesidad de hacer
ejercicio para no perder músculo, sobre todo es importante hacer
ejercicios de fuerza para que este proceso de reparación ocurra.
Fasting, coge la energia de la grasa visceral, pero también del músculo,
pero luego reconstruye el músculo. Por eso en los ensayos ven que se
pierde grasa visceral, pero no del musculo, porque el musculo se
regenera luego. Por eso los atletas están empezando a interesarse en
FMD. Porque quieren músculo, pero menos grasa. Y con esto se consigue.

*Mitophagy*: The selective degradation of mitochondria by autophagy. It
usually occurs to defective mitochrondia following damage or stress.
